local mapper = require("meta_mapper")
local helpers = require("tests.helpers")

describe("meta_mapper.extract_tls", function()
  it("returns no tls configs if config has no tls blocks", function()
    local config = helpers.load_fixture("vmess-simple.json")
    local new_config, tls_configs, bindings = mapper.extract_tls(config)
    assert.equal(0, #tls_configs)
    assert.same({}, bindings.inbound)
    assert.same({}, bindings.outbound)
    assert.is_nil(new_config.inbounds[1].tls_id)
  end)

  it("extracts tls block from inbound and replaces with tls_id", function()
    local config = helpers.load_fixture("trojan-tls.json")
    local new_config, tls_configs, bindings = mapper.extract_tls(config)
    assert.equal(1, #tls_configs)
    assert.equal(1, tls_configs[1].id)
    assert.equal("example.com", tls_configs[1].tls.server_name)
    assert.equal(1, bindings.inbound["trojan-in"])
    assert.is_nil(new_config.inbounds[1].tls)
    assert.equal(1, new_config.inbounds[1].tls_id)
  end)

  it("deduplicates identical tls blocks across inbounds", function()
    local config = helpers.load_fixture("multi-tls.json")
    local new_config, tls_configs, bindings = mapper.extract_tls(config)
    assert.equal(2, #tls_configs)
    assert.equal(bindings.inbound["vless-in-1"], bindings.inbound["trojan-in-2"])
    assert.is_truthy(bindings.outbound["vless-out"])
    assert.are_not.equal(bindings.inbound["vless-in-1"], bindings.outbound["vless-out"])
  end)
end)

describe("meta_mapper.extract_clients", function()
  it("extracts users from vmess inbound into clients", function()
    local config = helpers.load_fixture("vmess-simple.json")
    local _, clients, bindings = mapper.extract_clients(config)
    assert.equal(2, #clients)
    assert.equal("alice", clients[1].name)
    assert.is_table(clients[1].config.vmess)
    assert.equal("11111111-1111-1111-1111-111111111111", clients[1].config.vmess.uuid)
    assert.same({1, 2}, bindings["vmess-in"])
  end)

  it("merges identical clients across multiple inbounds by name", function()
    local config = helpers.load_fixture("multi-tls.json")
    local _, clients, bindings = mapper.extract_clients(config)
    assert.equal(1, #clients)
    assert.equal("alice", clients[1].name)
    assert.is_table(clients[1].config.vless)
    assert.is_table(clients[1].config.trojan)
    assert.same({1}, bindings["vless-in-1"])
    assert.same({1}, bindings["trojan-in-2"])
  end)
end)

describe("meta_mapper.load", function()
  it("composes extract_tls + extract_clients into store-shaped object", function()
    local config = helpers.load_fixture("vless-reality.json")
    local result = mapper.load(config, nil)
    assert.is_table(result.config)
    assert.equal("info", result.config.log.level)
    assert.equal(1, #result.inbounds)
    assert.equal(1, result.inbounds[1].tls_id)
    assert.is_nil(result.inbounds[1].tls)
    assert.equal(1, #result.tls)
    assert.equal(1, #result.clients)
    assert.equal("alice", result.clients[1].name)
  end)

  it("preserves tls config name from existing meta", function()
    local config = helpers.load_fixture("trojan-tls.json")
    local existing_meta = {
      tlsConfigs = {
        { id = 5, name = "my-cert", tls = config.inbounds[1].tls }
      }
    }
    local result = mapper.load(config, existing_meta)
    assert.equal("my-cert", result.tls[1].name)
  end)
end)
