local sui_config = require("sui_config")

describe("sui_config", function()
  it("returns defaults when file is missing", function()
    local cfg = sui_config.load("/nonexistent")
    assert.equal("/etc/sing-box/config.json", cfg.singbox_config_path)
    assert.equal("http://127.0.0.1:9090", cfg.clash_api_url)
  end)

  it("overrides defaults from file", function()
    local p = os.tmpname()
    local f = io.open(p, "w")
    f:write("singbox_config_path=/tmp/cfg.json\nclash_api_secret=hunter2\n")
    f:close()
    local cfg = sui_config.load(p)
    assert.equal("/tmp/cfg.json", cfg.singbox_config_path)
    assert.equal("hunter2", cfg.clash_api_secret)
    assert.equal("http://127.0.0.1:9090", cfg.clash_api_url)
    os.remove(p)
  end)
end)
