local util = require("util")

describe("util.read_file", function()
  it("returns content of existing file", function()
    local tmp = os.tmpname()
    local f = io.open(tmp, "w"); f:write("hello"); f:close()
    assert.equal("hello", util.read_file(tmp))
    os.remove(tmp)
  end)

  it("returns nil for missing file", function()
    assert.is_nil(util.read_file("/nonexistent/path/xyz"))
  end)
end)

describe("util.write_file_atomic", function()
  it("writes content and renames", function()
    local tmp = os.tmpname()
    os.remove(tmp)
    local ok, err = util.write_file_atomic(tmp, "data")
    assert.is_true(ok, err)
    assert.equal("data", util.read_file(tmp))
    os.remove(tmp)
  end)

  it("preserves old content if write fails (bad path)", function()
    local ok, err = util.write_file_atomic("/nonexistent/dir/file", "x")
    assert.is_false(ok)
    assert.is_string(err)
  end)
end)

describe("util.exec", function()
  it("returns stdout and exit code 0 for echo", function()
    local out, code = util.exec("echo hello")
    assert.equal("hello\n", out)
    assert.equal(0, code)
  end)

  it("returns nonzero exit code for false", function()
    local _, code = util.exec("false")
    assert.is_true(code ~= 0)
  end)
end)

describe("util.json", function()
  it("decodes file content", function()
    local tmp = os.tmpname()
    local f = io.open(tmp, "w"); f:write('{"a":1,"b":[2,3]}'); f:close()
    local obj = util.read_json(tmp)
    assert.same({a=1, b={2,3}}, obj)
    os.remove(tmp)
  end)

  it("returns nil + err on invalid json", function()
    local tmp = os.tmpname()
    local f = io.open(tmp, "w"); f:write("{not json"); f:close()
    local obj, err = util.read_json(tmp)
    assert.is_nil(obj)
    assert.is_string(err)
    os.remove(tmp)
  end)

  it("encodes pretty with sorted keys", function()
    local s = util.encode_json({b=2, a=1})
    assert.is_string(s)
    local back = require("cjson").decode(s)
    assert.same({a=1, b=2}, back)
  end)
end)
