local util = require("util")

describe("util.read_file", function()
  it("returns content of existing file", function()
    local tmp = os.tmpname()
    local f = io.open(tmp, "w"); f:write("hello"); f:close()
    assert.equal("hello", util.read_file(tmp))
    os.remove(tmp)
  end)

  it("returns nil for missing file", function()
    assert.is_nil(util.read_file("/nonexistent/path/xyz"))
  end)
end)

describe("util.write_file_atomic", function()
  it("writes content and renames", function()
    local tmp = os.tmpname()
    os.remove(tmp)
    local ok, err = util.write_file_atomic(tmp, "data")
    assert.is_true(ok, err)
    assert.equal("data", util.read_file(tmp))
    os.remove(tmp)
  end)

  it("preserves old content if write fails (bad path)", function()
    local ok, err = util.write_file_atomic("/nonexistent/dir/file", "x")
    assert.is_false(ok)
    assert.is_string(err)
  end)
end)
