local mapper = require("meta_mapper")
local helpers = require("tests.helpers")

describe("meta_mapper.extract_tls", function()
  it("returns no tls configs if config has no tls blocks", function()
    local config = helpers.load_fixture("vmess-simple.json")
    local new_config, tls_configs, bindings = mapper.extract_tls(config)
    assert.equal(0, #tls_configs)
    assert.same({}, bindings.inbound)
    assert.same({}, bindings.outbound)
    assert.is_nil(new_config.inbounds[1].tls_id)
  end)

  it("extracts tls block from inbound and replaces with tls_id", function()
    local config = helpers.load_fixture("trojan-tls.json")
    local new_config, tls_configs, bindings = mapper.extract_tls(config)
    assert.equal(1, #tls_configs)
    assert.equal(1, tls_configs[1].id)
    assert.equal("example.com", tls_configs[1].tls.server_name)
    assert.equal(1, bindings.inbound["trojan-in"])
    assert.is_nil(new_config.inbounds[1].tls)
    assert.equal(1, new_config.inbounds[1].tls_id)
  end)

  it("deduplicates identical tls blocks across inbounds", function()
    local config = helpers.load_fixture("multi-tls.json")
    local new_config, tls_configs, bindings = mapper.extract_tls(config)
    assert.equal(2, #tls_configs)
    assert.equal(bindings.inbound["vless-in-1"], bindings.inbound["trojan-in-2"])
    assert.is_truthy(bindings.outbound["vless-out"])
    assert.are_not.equal(bindings.inbound["vless-in-1"], bindings.outbound["vless-out"])
  end)
end)
